/* -------------------------------------------------------
 * WARNING:
 *
 * This code was generated by the Excel Importer
 * Any changes will be lost, when it gets regenerated.
 * -----------------------------------------------------*/

using ExcelImporter.Editor.ExcelProcessing;
using ExcelImporter.Editor.Importing;
using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Game.Data.Imports
{
    public class TestDataWorkbookImporter_TEMPLATE
    {
        private const string ExcelFilePath = "Assets/Packages/ExcelImporter/TestData.xlsx";
        private const string ImportBasePath = "Assets/Data/Imports/";
        private const bool PrefixAssetName = true;
        private const bool FindAdditionalWorkbooks = true;

        //[MenuItem("Tools/Excel Importer/Import TestDataWorkbookImporter", priority = 300)]
        public static void Import()
        {
            try
            {
                EditorUtility.DisplayProgressBar("Excel Importer", "Loading Workbook", 0f);
                var workbook = ExcelWorkbookFactory.Create(ExcelFilePath);

                EditorUtility.DisplayProgressBar("Excel Importer", "Importing Sheet: TestThings", 1f);
                HandleSheet<TestThingsImport_TEMPLATE, TestThingsImport_TEMPLATE.Row>(workbook, "TestThings");



                EditorUtility.DisplayProgressBar("Excel Importer", "Saving Assets", 1f);
                AssetDatabase.SaveAssets();

                UnityEngine.Debug.Log($"Imported {workbook.Sheets.Count} sheets from {workbook.FilePath}");
            }
            catch (Exception e)
            {
                EditorUtility.DisplayDialog(nameof(TestDataWorkbookImporter_TEMPLATE), "Import Failed! See console log for details", "Ok");
                UnityEngine.Debug.LogError(e);
            }

            EditorUtility.ClearProgressBar();
        }

        private static void HandleSheet<TSheet, TRow>(ExcelWorkbook workbook, string sheetName)
            where TSheet : ScriptableObject
            where TRow : new()
        {
            var importFilename = GetImportFilePath(workbook, sheetName, ImportBasePath, PrefixAssetName);
            SheetImporter.ImportData<TSheet, TRow>(workbook, sheetName, importFilename);
        }

        private static string GetImportFilePath(ExcelWorkbook workbook, string sheetName, string importBasePath, bool prefixAssetName)
        {
            var prefix = prefixAssetName ? $"{workbook.Name}." : string.Empty;
            var filename = $"{prefix}{sheetName}.asset";

            return Path.Combine(importBasePath, filename);
        }
    }
}
